#!/bin/sh

set -e

scripts=$(dirname "$0")
root="$scripts/.."
gogen="$root/cmd/x86db-gogen"

curl -s --show-error -o "$scripts/amd64enc.s" https://raw.githubusercontent.com/golang/go/master/src/cmd/asm/internal/asm/testdata/amd64enc.s

cat <<EOF > "$gogen/tested_map.go"
// generated by $0
// DO NOT EDIT

package main

var testedMap = map[string]bool{
EOF

instructions=$(grep -v TODO "$scripts/amd64enc.s" | cut -f 1 -d ' ' | tr -d '\t' | sort -u)

for i in $instructions; do
	echo "	\"$i\": true," >> $gogen/tested_map.go
done

cat <<EOF >> "$gogen/tested_map.go"
}
EOF

rm "$scripts/amd64enc.s"
